spring:
  application:
    name: wallet

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /docs

jwt:
  secret: ${JWT_SECRET:xK9#mN2@pQ7rS5tU8vW1xY4zA6bC0dE3fG8hI1jK4lM7nO0pQ3rS6tU9vW2x}
