spring:
  application:
    name: wallet

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://reseau.proxy.rlwy.net:27450/railway}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:ecQQtASlPXVyqaBjPfywXGbQNesWMqvc}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME:14ffffdcd146ec}
    password: ${MAIL_PASSWORD:0343cab8f8f6e1}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /docs
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.digitalwallet.wallet

server:
  forward-headers-strategy: framework
  tomcat:
    use-relative-redirects: true

jwt:
  secret: ${JWT_SECRET:xK9#mN2@pQ7rS5tU8vW1xY4zA6bC0dE3fG8hI1jK4lM7nO0pQ3rS6tU9vW2x}
